wsdmm_gui/apps/shunt/urls.py
###############################################################################
# Shunt Application URL Dispatch
#
# COPYRIGHT
# | All rights reserved (c) 2020 ALSTOM, USA
# |
# | This computer program may not be used, copied, distributed,
# | corrected, modified, translated, transmitted or assigned
# | without ALSTOM's prior written authorization.
###############################################################################
from django.urls import path
from . import views

app_name = 'shunt'
urlpatterns = [
    path('', views.index, name='index'),
    path('config/', views.config, name='config'),
    path('config/update', views.update, name='update'),
    path('config/startstop', views.startStop, name='startstop'),
    path('config/<str:processor_name>', views.config, name='config'),
]

wsdmm_gui/apps/tcm/urls.py
###############################################################################
# TCM Application URL Dispatch
#
# COPYRIGHT
# | All rights reserved (c) 2020 ALSTOM, USA
# |
# | This computer program may not be used, copied, distributed,
# | corrected, modified, translated, transmitted or assigned
# | without ALSTOM's prior written authorization.
###############################################################################
from django.urls import path
from . import views

app_name = 'tcm'
urlpatterns = [
    path('', views.index, name='index'),
    path('config/', views.config, name='config'),
    path('config/update', views.update, name='update'),
    path('config/startstop', views.startStop, name='startstop'),
    path('config/<str:processor_name>', views.config, name='config'),
    path('plot/', views.plot, name='plot'),
]

wsdmm_gui/wsdmm_gui/urls.py
##############################################################################
# Main WSDMM GUI URL Dispatch
#
# COPYRIGHT
# | All rights reserved (c) 2020, USA
# |
# | This computer program may not be used, copied, distributed,
# | corrected, modified, translated, transmitted or assigned
# | without ALSTOM's prior written authorization.
##############################################################################
"""wsdmm_gui URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('apps.main.urls')),
    path('admin/', admin.site.urls, name='admin'),
    path('shunt/', include('apps.shunt.urls')),
    path('shunt/csv/', include('apps.csvbrowse.urls')),
    path('logcap/', include('apps.logcap.urls')),
    path('tcm/', include('apps.tcm.urls')),
]

if bool(settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

wsdmm_gui/apps/tcm/models.py
###############################################################################
# The data model for the Shunt NiFi django app.
#
# The goal here is to provide just enough information for django to interact
# with the shunt NiFi app - nothing more.  All other data is stored in NiFi.
#
# COPYRIGHT
# | All rights reserved (c) 2020 ALSTOM, USA
# |
# | This computer program may not be used, copied, distributed,
# | corrected, modified, translated, transmitted or assigned
# | without ALSTOM's prior written authorization.
###############################################################################
from django.db import models


class tcm(models.Model):
    # Hostname of the target NiFi instance
    hostname = models.CharField(max_length=256)
    # Port of the target NiFi instance
    hostport = models.IntegerField(default=8090)

    def __str__(self):
        return self.hostname + ":" + str(self.hostport)

wsdmm_gui/apps/tcm/views.py
###############################################################################
# This is the django views modules for the TCM NiFi Django project.  It is
# intended to be used within a django app for managing a NiFi tcm install
# through its REST interface.
#
# Contact: andrew.vaselaar@alstomgroup.com
#
# COPYRIGHT
# | All rights reserved (c) 2020 ALSTOM, USA
# |
# | This computer program may not be used, copied, distributed,
# | corrected, modified, translated, transmitted or assigned
# | without ALSTOM's prior written authorization.
###############################################################################
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django import forms

from tempus_dominus.widgets import DateTimePicker

from common.wsdmmapi import wsdmmapi as wapi

from datetime import datetime, timedelta
import logging
import re
import json

api = wapi.wsdmmapi('tcm')
dbapi = wapi.wsdmmapi('influx')

logger = logging.getLogger(__name__)


@api.check
def index(request):
    r = api.get('status/service/tcm')
    if r.status_code == 200:
        data = r.json()
        status = {}
        for key in data['status']:
            status[key.replace('_', '')] = data['status'][key]
        context = {
            'hostname': data['hostname'],
            'port': data['hostport'],
            'service': data['service'],
            'status': status
        }
    else:
        context = {
            'hostname': 'none',
            'port': 'none',
            'service': 'none'
        }
    return render(request, 'tcm/index.html', context)


@api.check
def config(request, processor_name=''):
    track_ids = api.getTrackIDs('tcm')

    if processor_name == '':
        processor_name = track_ids[0]

    # Populate the processor List
    r = api.get('conf/tcm')
    data = r.json()
    nav = {}
    for item in data.items():
        nav[item[0]] = item[1]['name']

    # Populate the Form
    if len(processor_name) == 3 and re.match('[1-9]_[1-2]', processor_name):
        r = api.get('conf/tcm/track/' + processor_name)
    else:
        r = api.get('conf/tcm/mqtt/' + processor_name)
    data = r.json()
    context = {
        'status': 1,
        'track_ids': track_ids,
        'nav': nav,
        'pdispname': nav[processor_name],
        'fields': data,
        'processor': processor_name,
    }
    return render(request, 'tcm/config.html', context)


@api.check
def update(request):
    processor_name = request.POST['processor']
    url, name = api.pURLName(processor_name)
    r = api.get(url)
    fields = r.json()
    for key in fields:
        fields[key] = request.POST[key]
    r = api.postJSON(url, fields)
    return HttpResponseRedirect(reverse('tcm:config'))


@api.check
def startStop(request):
    if request.POST['control'] == "start":
        api.get('sched/tcm?desired_state=True')
    if request.POST['control'] == "stop":
        api.get('sched/tcm?desired_state=False')
    return HttpResponseRedirect(reverse('tcm:index'))


@api.check
@dbapi.check
def plot(request):
    # Empty dict for data
    data = {
        'meanCurrent': [],
        'operating_margin_max': [],
        'operating_margin_min': [],
        'blowby_threshold': [],
        'dropout_threshold': [],
        'reliability_margin': [],
        'safety_margin': [],
    }
    track_ids = api.getTrackIDs('tcm')

    # Start time/end time in datetime objects
    # IF this is in service in 2038, something has gone horribly wrong.
    time_format_string = "%Y-%m-%d %H:%M"
    timenow = datetime.today()
    if 'Begin' in request.GET:
        start_time = datetime.strptime(request.GET['Begin'], time_format_string)
    else:
        start_time = timenow - timedelta(seconds=24 * 60 * 60)  # default 1 day

    logger.debug(start_time)

    if 'End' in request.GET:
        end_time = datetime.strptime(request.GET['End'], time_format_string)
    else:
        end_time = timenow

    if 'track' in request.GET:
        track = request.GET['track']
    else:
        track = track_ids[0]

    # Which track do we want data for, and submit query
    if track in track_ids:
        r = api.get(str.format('data/tcm?startTime={}&endTime={}&track={}', int(start_time.timestamp()), int(end_time.timestamp()), track))
        if r.status_code == 200:
            plotdata = json.loads(r.json())
            for series in data:
                for x, value in plotdata.items():
                    data[series].append({'x': int(x) / 1000, 'y': value[series]})
        else:
            data = None

    form = dateForm()

    initial_date = {
        'start_time': start_time.strftime("%Y-%m-%d %H:%M"),
        'end_time': end_time.strftime("%Y-%m-%d %H:%M"),
    }

    context = {
        'track': track,
        'track_ids': track_ids,
        'initial_date': initial_date,
        'data': data,
        'form': form,
    }

    return render(request, 'tcm/plot.html', context)


class dateForm(forms.Form):
    Begin = forms.DateTimeField(
        widget=DateTimePicker(
            options={
                'format': "YYYY-MM-DD HH:mm",
                'collapse': False,
            },
            attrs={
                'append': 'fa fa-calendar',
                'icon_toggle': True,
            }
        ),
    )

    End = forms.DateTimeField(
        widget=DateTimePicker(
            options={
                'format': "YYYY-MM-DD HH:mm",
                'collapse': False,
            },
            attrs={
                'append': 'fa fa-calendar',
                'icon_toggle': True,
            }
        ),
    )

wsdmm_gui/apps/tcm/templates/tcm/config.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>TCMA Configuration</title>
{% endblock %}

{% block nav-tcm %}
<li class="nav-item active p-2">
	<a class="nav-link" href="{% url 'tcm:index'%}">Tcma</a>
</li>
{% endblock %}

{% block app_nav_brand %}
<a class="navbar-brand" href="#"><h5>TCMA Configuration</h5></a>
{% endblock %}

{% block app_tcm_submenu_show %}
show
{% endblock %}

{% block tcm_nav_item1 %}
{% endblock %}
{% block tcm_nav_item2 %}
active
{% endblock %}
{% block tcm_nav_item3 %}
{% endblock %}

{% block body %}
<div class="container-flex">
	<div class="row justify-content-right">
		<div class="col-sm-3">

			<hr class="mt-0 mb-4">
			<h4>Configuration</h4>
			<ul class="nav flex-column">
				{% for processor, name in nav.items|dictsort:0 %}
				<li class="nav-item">
					<a class="nav-link" href="{% url 'tcm:config' processor %}">{{ name }}</a>
				</li>
				{% endfor %}
			</ul>
		</div>

		<div class="col-sm-6">
			<h1>TCM Configuration</h1>
			<hr class="mt-0 mb-4">
			{% if status > 0 %}
			<div class="alert alert-danger" role="alert">
				The TCM monitoring application will be restarted when these
				properties are edited.
			</div>
			{% else %}
			<div class="alert alert-dark" role="alert">
				NIFI NOT AVAILABLE
			</div>
			{% endif %}
			<form action="{% url 'tcm:update' %}" method="post">
				{% csrf_token %}
				<h3>{{ pdispname }}</h3>
				<div class="form-group">
					<table class="table">
						<tbody>
					{% for key, value in fields.items %}
							<tr>
								<td><label for="{{ key }}">{{ key }}</label></td>
								<td>{{ value.description }}</td>
								<td style="min-width:400px"><input type="{% if value.type == "integer" or value.type == "number" %}number{% else %}string{% endif %}" class="form-control form-control-sm" name="{{ key }}" id="{{ key }}" value="{{ value.value }}"></td>
							</tr>
					{% endfor %}
						</tbody>
					</table>
				</div>
				<input type="hidden" id="processor" name="processor" value="{{ processor }}">
				<input type="submit" class="btn btn-primary" value="update">
			</form>
		</div>
	</div>
</div>
{% endblock %}

wsdmm_gui/apps/tcm/templates/tcm/index.html
{% extends 'base.html' %}
{% load static %}

{% load crispy_forms_tags %}

{% block head %}
<title>Track Circuit Health Monitoring</title>
{% endblock %}

{% block nav-shunt %}
<li class="nav-item active p-2">
	<a class="nav-link" href="{% url 'shunt:index'%}">Shunt</a>
</li>
{% endblock %}

{% block app_nav_brand %}
<a class="navbar-brand" href="#"><h5>Track Circuit Health</h5></a>
{% endblock %}

{% block app_tcm_submenu_show %}
show
{% endblock %}

{% block tcm_nav_item1 %}
active
{% endblock %}
{% block tcm_nav_item2 %}
{% endblock %}
{% block tcm_nav_item3 %}
{% endblock %}
{% block tcm_nav_item4 %}
{% endblock %}

{% block body %}
<div class="container-fluid">
	<div class="row justify-content-left">
		<h1>TCM Status</h1>
	</div>
	<hr class="mt-0 mb-4"></hr>
	<div class="row justify-content-center">
		<p>The NiFi TCM instance at http://{{ hostname }}:{{port}}/nifi-api is:</p>
	</div>
	<div class="row justify-content-center">
		{% if status.stoppedcount > 0 %}
		<div class="alert alert-danger" role="alert">
			<center>STOPPED</center>
		</div>
		{% endif %}
		{% if status.runningcount > 0 %}
		<div class="alert alert-success" role="alert">
			<center>RUNNING</center>
		</div>
		{% endif %}
		{% if status.runningcount < 0 %}
		<div class="alert alert-dark" role="alert">
			<center>NIFI NOT AVAILABLE</center>
			{% endif %}
		</div>
		{% if status.disabledcount > 0 %}
		<div class="alert alert-danger" role="alert">
			<center>Note: Some processors disabled. Check NiFi Flow.</center>
		</div>
		{% endif %}
	</div>
	<div class="row justify-content-center">
		<form action="{% url 'tcm:startstop' %}" method="post">
			{% csrf_token %}
			<div class="btn-group">
				<button class="btn btn-danger" type="submit" name="control" value="stop">Stop</button>
				<button class="btn btn-success" type="submit" name="control" value="start">Start</button>
			</div>
		</form>
	</div>
	<div class="row justify-content-left">
		<div class="card" style="width: 16rem;">
			<h5 class="card-title">NiFI Process Group Status</h5>
			<div class="card-body">
				<ul class="list-group list-group-flush">
					<li class="list-group-item"><strong>Disabled:</strong> <span class="btn btn-danger ">{{ status.disabledcount }}</span></li>
					<li class="list-group-item"><strong>Running:</strong> <span class="btn btn-success ">{{ status.runningcount }}</span></li>
					<li class="list-group-item"><strong>Stopped:</strong> <span class="btn btn-warning ">{{ status.stoppedcount }}</span></li>
				</ul>
			</div>
		</div>
	</div>
					{% if status.bulletins %}
	<div class="row justify-content-left">
		<div class="card" >
			<div class="card-body">
				<div class="row justify-content-center">
				<div class="alert alert-danger" role="alert">
					{% for bulletin in status.bulletins %}
					<p>	{{ status.bulletins }}</p>
					{% endfor %}

				</div>
			</div>
		</div>
	</div>
	{% endif %}
</div>
{% endblock %}

wsdmm_gui/apps/tcm/templates/tcm/plot.html
{% extends 'base.html' %}
{% load static %}

{% load crispy_forms_tags %}

{% block head %}
<title>Track Circuit Health Monitoring</title>
<style>
 .column { display: inline-block }
 #legend { background: white }
 #legend .line { color: #333 }
</style>
<link rel="stylesheet" type="text/css" href="{% static "rickshaw/rickshaw.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "rickshaw/lines.css" %}">
<link type="text/css" rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css">
{% endblock %}
{% block script %}
<script type="text/javascript" src="{% static "d3/d3.v3.js" %}"></script>
<script type="text/javascript" src="{% static "rickshaw/rickshaw.min.js" %}"></script>
{{ form.media }}

<style type="text/css">
 .rotatea {
  transform: rotate(-90deg);
 }
 .rotateb {
  transform: rotate(90deg);
 }
 #y-axis0 {
     position: absolute;
     left: 40px;
     height: 800px;
     width: 40px;
 }
 #y-title0 {
     position: absolute;
     left: -30px;
     top: 200px;
     width: 150px;
 }
 #y-axis1 {
     position: absolute;
     left: 975px;
     height: 800px;
     width: 60px;
 }
 #y-title1 {
     position: absolute;
     left: 940px;
     top: 210px;
     width: 150px;
 }
 #chart {
     left: 75px;
     width: 1000px;
     position: absolute;
 }
 #x-title {
     left: 525px;
     top: 500px;
     position: absolute;
 }
 #slider {
     left: 65px;
     top: 530px;
     width: 1000px;
     position: absolute;
 }
 #legend {
     left: -10px;
     position: absolute;
 }
</style>
{% endblock %}

{% block nav-tcm %}
<li class="nav-item active p-2">
    <a class="nav-link" href="{% url 'tcm:index'%}">Track Circuit Margins</a>
</li>
{% endblock %}

{% block app_nav_brand %}
<a class="navbar-brand" href="#"><h5>Track Circuit Health</h5></a>
{% endblock %}

{% block app_tcm_submenu_show %}
show
{% endblock %}

{% block tcm_nav_item1 %}
{% endblock %}
{% block tcm_nav_item2 %}
{% endblock %}
{% block tcm_nav_item3 %}
active
{% endblock %}
{% block tcm_nav_item4 %}
{% endblock %}

{% block body %}
<div class="container-flex">
    <div class="row justify-content-right">
        <div class="col-sm-2 d-print-none flex-expand-1">
            <form method="get" action="{% url 'tcm:plot' %}">
                <h6>Slot - Track</h6>
                <hr class="mt-0 mb-1">
                {% for track_id in track_ids %}
                <div class="form-check">
                    <label class="form-check-label">
                        <input type="radio" class="form-check-input" name="track" value="{{ track_id }}"
                        {% if track == track_id %}checked{% endif %}>Track {{ track_id }}
                    </label>
                </div>
                {% endfor %}
                <div class="mt-4">
                <h6>Time</h6>
                </div>
                <hr class="mt-0 mb-1">
                {{ form }}
                <div class="mt-1">
                <input type="submit" value="Update">
                </div>
            </form>
                <div class="mt-4">
        {% if data.meanCurrent %}
            <h6>Legend</h6>
                </div>
            <hr class="mt-0 mb-1">
            <div>
                <div id="legend"></div>
            </div>
        </div>
        <div class="col-sm-2 d-print-none flex-expand-1">
            <div class="col-sm-3">
                <div class="column">
                    <div id="y-axis0"></div>
                    <div id="y-title0" class="rotatea">Current (Amps)</div>
                    <div id="chart"></div>
                    <div id="y-axis1"></div>
                    <div id="y-title1" class="rotateb">Margin (Percentage)</div>
                    <div id="x-title">Time</div>
                    <div id="slider"></div>
                </div>
            </div>
        </div>
        {% else %}
        <h6>Please select a track and time window </h6>
        {% endif %}
    </div>
</div>
{% endblock %}
{% block bodyscript %}
<script>
 $('#id_Begin').datetimepicker('date', "{{ initial_date.start_time }}");
 $('#id_End').datetimepicker('date', "{{ initial_date.end_time }}");

 scale_left =  d3.scale.linear().domain([0, 3]).nice();
 scale_right =  d3.scale.linear().domain([0, 100]).nice();

 data = [
     {{data.meanCurrent|safe}},
     {{data.operating_margin_max|safe}},
     {{data.operating_margin_min|safe}},
     {{data.blowby_threshold|safe}},
     {{data.dropout_threshold|safe}},
     {{data.reliability_margin|safe}},
     {{data.safety_margin|safe}},
 ];


        {% if data.meanCurrent %}
 series_list = [
     {
         name: 'Mean Current (Amps)',
         data: data[0],
         color: 'rgba(25, 170, 10, 0.4)',
         renderer: 'line',
         scale: scale_left,
         strokeWidth: 3
     },
     {
         name: 'Operating Margin - Max (Amps)',
         data: data[1],
         color: 'rgba(115, 205, 170, 0.4)',
         renderer: 'line',
         scale: scale_left,
         strokeWidth: 3
     },
     {
         name: 'Operating Margin - Min (Amps)',
         data: data[2],
         color: 'rgba(115, 205, 170, 0.3)',
         renderer: 'line',
         scale: scale_left,
         strokeWidth: 3
     },
     {
         name: 'Blowby Threshold (Amps)',
         data: data[3],
         color: 'rgba(225, 90, 80, 0.3)',
         renderer: 'line',
         scale: scale_left,
         strokeWidth: 3
     },
     {
         name: 'Dropout Threshold (Amps)',
         data: data[4],
         color: 'rgba(225, 90, 80, 0.3)',
         renderer: 'line',
         scale: scale_left,
         strokeWidth: 3
     },
     {
         name: 'Reliability Margin (Percent)',
         data: data[5],
         color: 'rgba(225, 90, 80, 0.3)',
         renderer: 'line',
         scale: scale_right,
         strokeWidth: 3
     },
     {
         name: 'Safety Margin (Percent)',
         data: data[6],
         color: 'rgba(225, 90, 80, 0.3)',
         renderer: 'line',
         scale: scale_right,
         strokeWidth: 3
     },

 ];

 var graph = new Rickshaw.Graph(
     {
         element: document.getElementById("chart"),
         renderer: 'multi',
         width: 900,
         height: 500,
         dotSize: 5,
         series: series_list,
     }
 );

 var xAxis = new Rickshaw.Graph.Axis.Time({
     graph: graph,
     ticksTreatment: 'glow',
     tickFormat: function(x){
         return new Date(x).toLocaleString();
     }
 });

 var yAxisl = new Rickshaw.Graph.Axis.Y.Scaled({
     element: document.getElementById('y-axis0'),
     graph: graph,
     orientation: 'left',
     scale: scale_left,
     tickFormat: Rickshaw.Fixtures.Number.formatKMBT,
 });

 var yAxisr = new Rickshaw.Graph.Axis.Y.Scaled({
     element: document.getElementById('y-axis1'),
     graph: graph,
     orientation: 'right',
     scale: scale_right,
     tickFormat: Rickshaw.Fixtures.Number.formatKMBT,
 });

 var slider = new Rickshaw.Graph.RangeSlider.Preview({
     graph: graph,
     element: document.getElementById('slider')
 });

 graph.render();

 var detail = new Rickshaw.Graph.HoverDetail({
     graph: graph
 });

 var legend = new Rickshaw.Graph.Legend({
     graph: graph,
     element: document.querySelector('#legend')
 });

 var highlighter = new Rickshaw.Graph.Behavior.Series.Highlight({
     graph: graph,
     legend: legend,
     disabledColor: function() { return 'rgba(0, 0, 0, 0.2)' }
 });

 var highlighter = new Rickshaw.Graph.Behavior.Series.Toggle({
     graph: graph,
     legend: legend
 });


        {% endif %}
</script>
{% endblock %}