wsdmm_gui/apps/csvbrowse/urls.py
###############################################################################
#  URL Dispatch for CSV Browser app
#
# Contact: andrew.vaselaar@alstomgroup.com
#
# COPYRIGHT
# | All rights reserved (c) 2020 ALSTOM, USA
# |
# | This computer program may not be used, copied, distributed,
# | corrected, modified, translated, transmitted or assigned
# | without ALSTOM's prior written authorization.
###############################################################################
from django.urls import path
from . import views

app_name = 'csvbrowse'
urlpatterns = [
    path('', views.indexView.as_view(), name='index'),
    path('<int:pk>/', views.csvView, name='detail'),
    path('download/<str:pk>/', views.downloadFile, name='download'),
    path('delete/<str:pk>/', views.deleteFile, name='delete'),
    path('chk/', views.chkBoxHandler, name='chkhandle'),
]

wsdmm_gui/apps/shunt/urls.py
###############################################################################
# Shunt Application URL Dispatch
#
# COPYRIGHT
# | All rights reserved (c) 2020 ALSTOM, USA
# |
# | This computer program may not be used, copied, distributed,
# | corrected, modified, translated, transmitted or assigned
# | without ALSTOM's prior written authorization.
###############################################################################
from django.urls import path
from . import views

app_name = 'shunt'
urlpatterns = [
    path('', views.index, name='index'),
    path('config/', views.config, name='config'),
    path('config/update', views.update, name='update'),
    path('config/startstop', views.startStop, name='startstop'),
    path('config/<str:processor_name>', views.config, name='config'),
]

wsdmm_gui/wsdmm_gui/urls.py
##############################################################################
# Main WSDMM GUI URL Dispatch
#
# COPYRIGHT
# | All rights reserved (c) 2020, USA
# |
# | This computer program may not be used, copied, distributed,
# | corrected, modified, translated, transmitted or assigned
# | without ALSTOM's prior written authorization.
##############################################################################
"""wsdmm_gui URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('apps.main.urls')),
    path('admin/', admin.site.urls, name='admin'),
    path('shunt/', include('apps.shunt.urls')),
    path('shunt/csv/', include('apps.csvbrowse.urls')),
    path('logcap/', include('apps.logcap.urls')),
    path('tcm/', include('apps.tcm.urls')),
]

if bool(settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

wsdmm_gui/apps/csvbrowse/models.py
###############################################################################
# Model Definition for the CSV browsing app
#
# Contact: andrew.vaselaar@alstomgroup.com
#
# COPYRIGHT
# | All rights reserved (c) 2020 ALSTOM, USA
# |
# | This computer program may not be used, copied, distributed,
# | corrected, modified, translated, transmitted or assigned
# | without ALSTOM's prior written authorization.
###############################################################################
from django.db import models
from django.utils import timezone


class ShuntCSV(models.Model):
    # Length of a CSV file in lines
    length_lines = models.IntegerField()
    # Track ID of the train move
    track_id = models.CharField(max_length=256)
    # Track ID of the train move
    slot_id = models.CharField(max_length=256)
    # Platform ID of the train move
    platform_id = models.CharField(max_length=256)
    # Full path to the file
    filename = models.CharField(max_length=256)
    # Just the basename of the file
    basename = models.CharField(max_length=256)
    # Status of LOS events in the file
    los_events = models.IntegerField()
    # Length of the train move itself
    train_length_timedelt = models.DurationField()
    # Timestamp of when the move occured
    train_timestamp = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.filename

wsdmm_gui/apps/csvbrowse/views.py
###############################################################################
# CSV Browser for Django
#
# Ideally, this would be completely independent of shunt.  Alas, it is not.
#
# Maybe someday.
#
# Contact: andrew.vaselaar@alstomgroup.com
#
# COPYRIGHT
# | All rights reserved (c) 2020 ALSTOM, USA
# |
# | This computer program may not be used, copied, distributed,
# | corrected, modified, translated, transmitted or assigned
# | without ALSTOM's prior written authorization.
###############################################################################
from django.http import HttpResponse, HttpResponseRedirect, FileResponse
from django.urls import reverse
from django.views import generic
from django.shortcuts import render, redirect
from django.core.files.storage import FileSystemStorage

from common.wsdmmconf import wsdmmconf as wc

import io
from datetime import datetime
import mimetypes
import zipfile
from urllib.request import pathname2url

from .models import ShuntCSV
from . import utils

from django.apps import apps
SiteData = apps.get_model('main', 'SiteData')

# TODO Grab this from the database
path = '/data/outfiles'  # the path where NiFi outputs csv
wsdmm_conf = '/data/infiles/wsdmm.conf'


class indexView(generic.ListView):
    """ A view to display a list of available CSV Files
    """
    template_name = 'csvbrowse/list.html'
    context_object_name = 'csv_files'
    model = ShuntCSV

    def updateFiles(self):
        """ Sync path directory with the database list of available CSV files
        """
        ds = wc.wsdmmconf()
        if ds.loadConfig(wsdmm_conf) is True:
            data = ds.getConfig()
            site_data = SiteData(
                Division=data['Division'],
                SubDivision=data['SubDivision'],
                LineSegment=data['LineSegment'],
                Milepost=data['Milepost'],
                DOTNum=data['DOT#'],
                StreetName=data['StreetName'],
                City=data['City'],
                State=data['State'],
                Country=data['Country'],
            )
        else:
            print("Missing: " + wsdmm_conf)
            return

        train_moves = utils.enumerateFiles(path, site_data)

        # Add new files to db
        for move in train_moves:
            if ShuntCSV.objects.filter(filename=move).exists() is False:
                if utils.checkFile(move) is True:
                    temp_name = move.rsplit('/', 1)[1]
                    temp_name = temp_name.rsplit('.', 1)[0]
                    metadata = utils.parseName(move)
                    length_lines, train_length, los_events = utils.getLength(move)
                    newobject = ShuntCSV(
                        filename=move,
                        length_lines=length_lines,
                        basename=temp_name,
                        track_id=metadata['track'],
                        slot_id=metadata['slot'],
                        platform_id=metadata['platform_id'],
                        los_events=los_events,
                        train_length_timedelt=train_length,
                        train_timestamp=metadata['date'])
                    newobject.save()
                else:
                    print("Unable to add file: " + move)

        # Remove stale/unreadable files from db
        for fileobject in ShuntCSV.objects.order_by('-filename'):
            if fileobject.filename not in train_moves:
                fileobject.delete()
            else:
                if utils.checkFile(fileobject.filename) is False:
                    fileobject.delete()

    def get_ordering(self):
        self.updateFiles()
        ordering = self.request.GET.get('ordering', '-train_timestamp')
        # validate ordering here
        return ordering

    def render_to_response(self, context):
        ds = wc.wsdmmconf()
        if ds.loadConfig(wsdmm_conf) is False:
            print("Site not configured. Missing config file")
            return redirect('main:configerror')
        return super().render_to_response(context)


class detailView(generic.DetailView):
    """ A page that shows some statistics (and soon a plot) about a CSV.
    """
    model = ShuntCSV
    template_name = 'csvbrowse/detail.html'


def plotCheck(pk, location='url'):
    fs = FileSystemStorage()
    csv = ShuntCSV.objects.get(pk=pk)
    pngname = getPlotName(csv.basename)
    if fs.exists(pngname) is False:
        try:
            filebuffer = utils.plotCSV(csv.filename, pngname[:-9])
            print("Plotting: " + pngname)
            status = fs.save(pngname, filebuffer)
            print("Save Status:" + str(status))
        except Exception as e:
            print("Plotting failed: " + str(e))
            return '', ''
    if location == "url":
        image_location = fs.url(pngname)
    elif location == "path":
        image_location = fs.path(pngname)
    return image_location, pngname


def csvView(request, pk):
    csv = ShuntCSV.objects.get(pk=pk)
    image_url, _ = plotCheck(pk)
    context = {'basename': csv.basename,
               'length_lines': csv.length_lines,
               'platform_id': csv.platform_id,
               'slot_id': csv.slot_id,
               'track_id': csv.track_id,
               'pngname': image_url,
               'los_events': csv.los_events,
               'train_time': csv.train_length_timedelt,
               'id': csv.id,
               }

    return render(request, 'csvbrowse/detail_plot.html', context)


def downloadFile(request, pk):
    """ Download a CSV file to the browser, selected by its pk.
    """
    the_object = ShuntCSV.objects.get(pk=pk)
    fl = open(the_object.filename, 'r')
    mime_type, _ = mimetypes.guess_type(the_object.filename)
    response = HttpResponse(fl, content_type=mime_type)
    response['Content-Disposition'] = "attachment; filename=%s" % pathname2url(the_object.filename)
    return response


def deleteHelper(pk):
    fs = FileSystemStorage()
    query = ShuntCSV.objects.filter(id=pk)
    for csv in query:
        # Delete from the filesystem
        status = utils.deleteFile(csv.filename)
        pngname = getPlotName(csv.basename)
        # Remove from the Database
        if status is True:
            csv.delete()
        # Delete plot if there is one
        if fs.exists(pngname) is True:
            fs.delete(pngname)


def deleteFile(request, pk):
    """ Delete a file from the CSV folder and the database, and any
        plots
    """
    deleteHelper(pk)
    response = HttpResponseRedirect(reverse('csvbrowse:index'))
    return response


def getPlotName(basename):
    return basename + '_plot.png'


def chkBoxHandler(request):
    """ Do things with the checkboxes on the list page.

        Either download the checked items in a zip, or delete
        them.
    """
    if request.POST['button'] == 'download_all':
        csv_list = ShuntCSV.objects.all().values_list('id', flat=True)
        response = downloadMultiple(csv_list)
    elif request.POST['button'] == 'delete_all':
        csv_list = ShuntCSV.objects.all().values_list('id', flat=True)
        for csv in csv_list:
            deleteHelper(csv)
        response = HttpResponseRedirect(reverse('csvbrowse:index'))
    elif len(request.POST.getlist('pk')) > 0:
        if request.POST['button'] == 'download':
            response = downloadMultiple(request.POST.getlist('pk'))
        if request.POST['button'] == 'delete':
            for item in request.POST.getlist('pk'):
                deleteHelper(item)
            response = HttpResponseRedirect(reverse('csvbrowse:index'))
    else:
        response = HttpResponseRedirect(reverse('csvbrowse:index'))
    return response


def downloadMultiple(download_list):
    """ Load up CSV files into a zip file, provide it as a download.

        Does not write to the hard disk - works in memory.
    """
    zipbuffer = io.BytesIO()  # Make an in-memory file buffer for zipfile
    now = datetime.now()    # Generate a timestamp
    name = now.strftime("%Y%m%d_%H%M%S") + "_shunt.zip"  # Generate filename
    try:  # Make a zipfile
        zf = zipfile.ZipFile(zipbuffer, mode='w',
                             compression=zipfile.ZIP_DEFLATED)
        for item in download_list:
            the_object = ShuntCSV.objects.get(pk=item)
            image_path, plot_filename = plotCheck(item, location='path')
            print("Zipping... " + the_object.filename)
            zf.write(the_object.filename, arcname=the_object.basename + ".csv")
            print("Zipping... " + plot_filename)
            zf.write(image_path, arcname=plot_filename)
        zf.close()
        zipbuffer.seek(0)
        response = FileResponse(zipbuffer, as_attachment=True, filename=name)
    except Exception as e:
        print("Unable to create zip file" + name + " " + str(e))
        response = HttpResponseRedirect(reverse('csvbrowse:index'))
    return response

wsdmm_gui/apps/csvbrowse/templates/csvbrowse/detail.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>{{ shuntcsv.basename }}</title>
{% endblock %}

{% block nav-shunt %}
<li class="nav-item active p-2">
	<a class="nav-link" href="{% url 'shunt:index'%}">Shunt</a>
</li>
{% endblock %}

{% block app_nav_brand %}
<a class="navbar-brand" href="#"><img src="{% static 'Picto_Alstom_Mainline_RGB_Carbonblue.png' %}" height=32></a>
<a class="navbar-brand" href="#"><h5>Shunt Monitoring</h5></a>
{% endblock %}

{% block app_nav_item1 %}
<li class="nav-item p-2">
	<a class="nav-link" href="{% url 'shunt:index' %}">Status</a>
</li>
{% endblock %}
{% block app_nav_item2 %}
<li class="nav-item p-2">
	<a class="nav-link" href="{% url 'shunt:config' %}">Configure</a>
</li>
{% endblock %}
{% block app_nav_item3 %}
<li class="nav-item active p-2">
	<a class="nav-link" href="{% url 'csvbrowse:index' %}">Files</a>
</li>
{% endblock %}

{% block body %}
<h2>Train Move Summary</h2>
<h4>{{ shuntcsv.basename }}</h4>
<table class="table-striped">
  <thead>
    <th scope"col">Property</th>
    <th scope"col">Value</th>
  </thead>
  <tbody>
    <tr><td>Number of Datapoints</td><td>{{shuntcsv.length_lines}}</td></tr>
    <tr><td>Elapsed Time (s)</td><td>{{shuntcsv.train_length_seconds}}</td></tr>
    <tr><td>Platform ID</td><td>{{shuntcsv.platform_id}}</td></tr>
  </tbody>
</table>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
{% endblock %}

wsdmm_gui/apps/csvbrowse/templates/csvbrowse/detail_plot.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>{{ shuntcsv.basename }}</title>
{% endblock %}

{% block nav-shunt %}
<li class="nav-item active p-2">
    <a class="nav-link" href="{% url 'shunt:index'%}">Shunt</a>
</li>
{% endblock %}

{% block app_nav_brand %}
<a class="navbar-brand" href="#"><h5>Shunt Monitoring</h5></a>
{% endblock %}

{% block app_shunt_submenu_show %}
show
{% endblock %}
{% block app_nav_item1 %}
{% endblock %}
{% block app_nav_item2 %}
{% endblock %}
{% block app_nav_item3 %}
{% endblock %}

{% block body %}
<div class="container">
    <div class="row justify-content-center">
        <h2>Train Move Summary</h2>
    </div>
    <div class="row justify-content-center">
    <a href="{% url 'csvbrowse:download' id %}">Download CSV</a>
    </div>
    <div class="row justify-content-center">
        <img src="{{ pngname }}" class="img-fluid" alt="Responsive image">
    </div>
    <div class="row justify-content-center">
        <table class="table-striped">
            <thead>
                <th scope"col">Property</th>
                <th scope"col">Value</th>
            </thead>
            <tbody>
                <tr><td>Filename</td><td>{{ basename }}</td></trtr>
                    <tr><td>Number of Datapoints</td><td>{{ length_lines }}</td></tr>
                    <tr><td>Platform ID</td><td>{{ platform_id }}</td></tr>
                    <tr><td>Slot ID</td><td>{{ slot_id }}</td></tr>
                    <tr><td>Track ID</td><td>{{ track_id }}</td></tr>
                    <tr><td>Events</td><td>{{ los_events }}</td></tr>
                    <tr><td>Train Duration</td><td>{{ train_time }}</td></tr>
            </tbody>
        </table>
    </div>
</div>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
{% endblock %}

wsdmm_gui/apps/csvbrowse/templates/csvbrowse/list.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>Train Moves</title>
{% endblock %}

{% block script %}
<script type="text/javascript" src="{% static "datatables/datatables.min.js" %}"></script>
<script type="text/javascript" src="{% static "datatables/DataTables-1.10.21/js/dataTables.jqueryui.min.js" %}"></script>
<script type="text/javascript" src="{% static "datatables/DataTables-1.10.21/js/dataTables.bootstrap4.min.js" %}"></script>
<script type="text/javascript" src="{% static "datatables/Buttons-1.6.2/js/dataTables.buttons.min.js" %}"></script>
<script type="text/javascript" src="{% static "datatables/Buttons-1.6.2/js/buttons.html5.min.js" %}"></script>
<script type="text/javascript" src="{% static "datatables/Buttons-1.6.2/js/buttons.bootstrap4.min.js" %}"></script>
{{ form.media }}
<script type="text/javascript" class="init">

 function filterGlobal () {
     $('#example').DataTable().search(
         $('#global_filter').val(),
         $('#global_regex').prop('checked'),
         $('#global_smart').prop('checked')
     ).draw();
 }

 function filterColumn ( i ) {
     $('#example').DataTable().column( i ).search(
         $('#col'+i+'_filter').val(),
         $('#col'+i+'_regex').prop('checked'),
         $('#col'+i+'_smart').prop('checked')
     ).draw();
 }
 $(document).ready(function() {
     $('#example').DataTable( {
         buttons: [
             'csv'
         ],
         select: true,
         "dom": 'tBilpr',
     } );

     $('input.global_filter').on( 'keyup click', function () {
         filterGlobal();
     } );

     $('input.column_filter').on( 'keyup click', function () {
         filterColumn( $(this).parents('tr').attr('data-column') );
     } );

 } );

</script>
<style type="text/css">
</style>
{% endblock %}

{% block nav-shunt %}
<li class="nav-item active p-2">
    <a class="nav-link" href="{% url 'shunt:index'%}">Shunt</a>
</li>
{% endblock %}

{% block app_nav_brand %}
<a class="navbar-brand" href="#"><h5>Shunt Monitoring</h5></a>
{% endblock %}

{% block app_shunt_submenu_show %}
show
{% endblock %}

{% block app_nav_item1 %}
{% endblock %}
{% block app_nav_item2 %}
{% endblock %}
{% block app_nav_item3 %}
active
{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row justify-content-left">
        <div class="col">
            <h1>Train Moves</h1>
            <hr class="mt-0 mb-4">
            <div class="table-responsive">
                <form action="{% url 'csvbrowse:chkhandle' %}" method="post">
                    {% csrf_token %}
                    <table id="example" class="table-striped table-bordered">
                        <thead>
                            <tr>
                                <th scope="col"></th>
                                <th style="text-align:center" scope="col">Download</th>
                                <th style="text-align:center" scope="col">Timestamp</th>
                                <th style="text-align:center" scope="col">Filename</th>
                                <th style="text-align:center" scope="col">Number of Data Points</th>
                                <th style="text-align:center" scope="col">Platform ID</th>
                                <th style="text-align:center" scope="col">Slot</th>
                                <th style="text-align:center" scope="col">Track ID</th>
                                <th style="text-align:center" scope="col">Events</th>
                                <th style="text-align:center" scope="col">Train Duration</th>
                                <th style="text-align:center" scope="col">DELETE</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for file in csv_files %}
                            <tr>
                                <th scope="col"><input type="checkbox" id="selected" name="pk" value="{{file.id}}"></th>
                                <td style="text-align:center"><a href="{% url 'csvbrowse:download' file.id %}">DL</a></td>
                                <td style="text-align:left"><a href="{% url 'csvbrowse:detail' file.id %}">{{file.train_timestamp}}</a></td>
                                <td style="text-align:center">{{file.basename}}</td>
                                <td style="text-align:center">{{file.length_lines}}</td>
                                <td style="text-align:center">{{file.platform_id}}</td>
                                <td style="text-align:center">{{file.slot_id}}</td>
                                <td style="text-align:center">{{file.track_id}}</td>
                                <td style="text-align:center">{{file.los_events}}</td>
                                <td style="text-align:center">{{file.train_length_timedelt}}</td>
                                <td style="text-align:center"><a href="{% url 'csvbrowse:delete' file.id %}">DELETE</a></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
            </div>
            <div class="btn-group">
                <button class="btn btn-success" type="submit" name="button" value="download">Download Selected</button>
            </div>
            <div class="btn-group">
                <button class="btn btn-success" type="submit" name="button" value="download_all">Download ALL</button>
            </div>
            <div class="btn-group">
                <button class="btn btn-danger float-right ml-5" type="submit" name="button" value="delete">Delete Selected</button>
            </div>
            <div class="btn-group">
                <button class="btn btn-danger" type="submit" name="button" value="delete_all">Delete ALL</button>
            </div>
                </form>
        </div>
    </div>
</div>
{% endblock %}