wsdmm_gui/apps/logcap/urls.py
###############################################################################
#  URL Dispatch for LogCap app
#
# Contact: andrew.vaselaar@alstomgroup.com
#
# COPYRIGHT
# | All rights reserved (c) 2020 ALSTOM, USA
# |
# | This computer program may not be used, copied, distributed,
# | corrected, modified, translated, transmitted or assigned
# | without ALSTOM's prior written authorization.
###############################################################################
from django.urls import path
from . import views

app_name = 'logcap'
urlpatterns = [
    path('', views.index, name='index'),
    path('config', views.config, name='config'),
    path('update', views.update, name='update'),
    path('logs/<int:timeframe>', views.logs, name='logs'),
    path('logs/', views.logs, name='logs'),
    path('config/startstop', views.startStop, name='startstop'),
    path('adddevice', views.addDevice, name='adddevice'),
    path('deldevice/<str:device_type>/<str:device_name>', views.delDevice, name='deldevice'),
    path('deviceconf/', views.showDeviceConf, name='deviceconf'),
    path('deviceconf/<str:device_type>/<str:device_name>', views.showDeviceConf, name='deviceconf'),
    path('adddeviceform/<str:device_type>', views.addDeviceForm, name='adddeviceform'),
    path('config/<str:device_type>/<str:device_name>', views.config, name='config'),
    path('rawlogs/', views.listRawLogs, name='rawlogs'),
    path('rawlogs/<str:device_type>/<str:device_name>', views.listRawLogs, name='rawlogs'),
    path('rawlogs/<str:device_type>/<str:device_name>/<str:filename>', views.listRawLogs, name='rawlogs'),
    path('rawlog/<str:device_type>/<str:device_name>/<str:filename>', views.rawLog, name='rawlog'),
    path('dlrawlog/<str:device_type>/<str:device_name>/<str:filename>', views.dlRawLog, name='dlrawlog'),
    path('dllatestraw/<str:device_type>/<str:device_name>', views.dlLatestRaw, name='dllatestraw'),
]

wsdmm_gui/apps/main/urls.py
###############################################################################
# The WSDMM GUI main app url page.
#
# Contact: andrew.vaselaar@alstomgroup.com
#
# COPYRIGHT
# | All rights reserved (c) 2020 ALSTOM, USA
# |
# | This computer program may not be used, copied, distributed,
# | corrected, modified, translated, transmitted or assigned
# | without ALSTOM's prior written authorization.
###############################################################################
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.index.as_view(), name='index'),
    path('config/location', views.config.as_view(), name='loc_config'),
    path('config/vti', views.vticonfig, name='vti_config'),
    path('config/updatevti', views.updatevti, name='update_vti'),
    path('configerror/', views.configerror, name='configerror'),
    path('status/', views.status, name='status'),
    path('about/', views.about, name='about'),
]

wsdmm_gui/apps/shunt/urls.py
###############################################################################
# Shunt Application URL Dispatch
#
# COPYRIGHT
# | All rights reserved (c) 2020 ALSTOM, USA
# |
# | This computer program may not be used, copied, distributed,
# | corrected, modified, translated, transmitted or assigned
# | without ALSTOM's prior written authorization.
###############################################################################
from django.urls import path
from . import views

app_name = 'shunt'
urlpatterns = [
    path('', views.index, name='index'),
    path('config/', views.config, name='config'),
    path('config/update', views.update, name='update'),
    path('config/startstop', views.startStop, name='startstop'),
    path('config/<str:processor_name>', views.config, name='config'),
]

wsdmm_gui/apps/tcm/urls.py
###############################################################################
# TCM Application URL Dispatch
#
# COPYRIGHT
# | All rights reserved (c) 2020 ALSTOM, USA
# |
# | This computer program may not be used, copied, distributed,
# | corrected, modified, translated, transmitted or assigned
# | without ALSTOM's prior written authorization.
###############################################################################
from django.urls import path
from . import views

app_name = 'tcm'
urlpatterns = [
    path('', views.index, name='index'),
    path('config/', views.config, name='config'),
    path('config/update', views.update, name='update'),
    path('config/startstop', views.startStop, name='startstop'),
    path('config/<str:processor_name>', views.config, name='config'),
    path('plot/', views.plot, name='plot'),
]

wsdmm_gui/wsdmm_gui/urls.py
##############################################################################
# Main WSDMM GUI URL Dispatch
#
# COPYRIGHT
# | All rights reserved (c) 2020, USA
# |
# | This computer program may not be used, copied, distributed,
# | corrected, modified, translated, transmitted or assigned
# | without ALSTOM's prior written authorization.
##############################################################################
"""wsdmm_gui URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('apps.main.urls')),
    path('admin/', admin.site.urls, name='admin'),
    path('shunt/', include('apps.shunt.urls')),
    path('shunt/csv/', include('apps.csvbrowse.urls')),
    path('logcap/', include('apps.logcap.urls')),
    path('tcm/', include('apps.tcm.urls')),
]

if bool(settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

wsdmm_gui/templates/base.html
{% load static %}
{% load fontawesome_5 %}

<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="{% static "bootstrap/4.4.1/css/bootstrap.min.css" %}" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static "datatables/datatables.min.css" %}">
        {% fontawesome_5_static %}
        <style>
         body {
             padding-top: 60px;
         }
         @media (max-width: 979px) {
             body {
                 padding-top: 0px;
             }
         }
         .navbar-custom-dark {
             background-color: #1e3246;
         }
         .navbar-custom-light {
             background-color: #d2d7dc;
         }

         .navbar-custom-light.active {
             background-color: #1e3246;
             border-color: #1e3246;
         }
         /* change the brand and text color */
         .navbar-custom .navbar-brand,
         .navbar-custom .navbar-text {
             color: rgba(30,50,70,.8);
         }
         /* change the link color */
         .navbar-custom .navbar-nav .nav-link {
             color: rgba(255,255,255,.5);
         }
         /* change the color of active or hovered links */
         .navbar-custom .nav-item.active .nav-link,
         .navbar-custom .nav-item:hover .nav-link {
             color: #ffffff;
         }
        </style>
        {% block head %}
        {% endblock %}
        <script src="{% static "jquery/jquery-3.2.1.slim.min.js" %}" crossorigin="anonymous"></script>
        <script src="{% static "popper/popper.min.js" %}" crossorigin="anonymous"></script>
        <script src="{% static "bootstrap/4.4.1/js/bootstrap.min.js" %}" crossorigin="anonymous"></script>
        {% block script %}
        {% endblock %}
    </head>
    <body>
        {% block nav %}
        <div class="wrapper container-fluid">
        <nav class="navbar fixed-top navbar-expand-lg navbar-dark navbar-custom-dark d-print-none">
            <a class="navbar-brand" href="{% url 'main:index' %}"><img src="{% static 'images/ALSTOM_WHITE no background.png' %}" height=32></a>
            <ul class="navbar-nav flex-row ml-md-auto d-md-flex">
                <li class="nav-item w-100">
                    <a class="nav-link" href="{% url 'main:index'%}">Home<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Configure
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'main:loc_config' %}">Site Information</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'main:vti_config' %}">VTI</a>
                        <a class="dropdown-item" href="{% url 'admin:index' %}">Servers</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Status
                    </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'main:status' %}">Device Statistics</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'main:about'%}">About</a>
                    </div>
                </li>
            </ul>
        </nav>
        <div>
        {% endblock %}

        <!-- Bootstrap row -->
        <div class="wrapper container-fluid">
        <div class="row" id="body-row">
            <!-- Sidebar -->
            <div id="sidebar-container" class="sidebar-expanded d-none d-md-block d-print-none">
                <!-- d-* hiddens the Sidebar in smaller devices. Its itens can be kept on the Navbar 'Menu' -->
                <!-- Bootstrap List Group -->
                <ul class="list-group">
                    <!-- Separator with title -->
                    <li class="list-group-item sidebar-separator-title text-muted d-flex align-items-center menu-collapsed">
                        <small>APPLICATIONS</small>
                    </li>
                    <!-- /END Separator -->
                    <!-- LogCap Menu with submenu -->
                    <a href="#logcap_submenu" data-toggle="collapse" aria-expanded="false"
                       class="navbar-custom-light list-group-item list-group-item-action flex-column align-items-start">
                        <div class="d-flex w-100 justify-content-start align-items-center">
                            <img src="{% static 'Picto_Alstom_Learning_RGB_Carbonblue.png' %}" height=24>
                            <span class="fa fa-dashboard fa-fw mr-3"></span>
                            <span class="menu-collapsed">LogCap</span>
                            <span class="submenu-icon ml-auto"></span>
                        </div>
                    </a>
                    <!-- Shunt Submenu content -->
                    <div id='logcap_submenu' class="collapse sidebar-submenu
                             {% block app_logcap_submenu_show %}

                             {% endblock %}">
                        <a href="{% url 'logcap:index' %}" class="list-group-item list-group-item-action
                                 navbar-custom-light
                                 {% block logcap_nav_item1 %}
                                 {% endblock %}">
                            <span class="menu-collapsed">Status</span>
                        </a>
                        <a href="{% url 'logcap:config' %}" class="list-group-item list-group-item-action
                                 navbar-custom-light
                                 {% block logcap_nav_item2 %}
                                 {% endblock %}">
                            <span class="menu-collapsed">Settings</span>
                        </a>
                        <a href="{% url 'logcap:logs' %}" class="list-group-item list-group-item-action
                                 navbar-custom-light
                                 {% block logcap_nav_item3 %}
                                 {% endblock %}">
                            <span class="menu-collapsed">Combined Logs</span>
                        </a>
                        <a href="{% url 'logcap:deviceconf' %}" class="list-group-item list-group-item-action
                                 navbar-custom-light
                                 {% block logcap_nav_item4 %}
                                 {% endblock %}">
                            <span class="menu-collapsed">Device Configuration</span>
                        </a>
                        <a href="{% url 'logcap:rawlogs' %}" class="list-group-item list-group-item-action
                                 navbar-custom-light
                                 {% block logcap_nav_item5 %}
                                 {% endblock %}">
                            <span class="menu-collapsed">Raw Logs</span>
                        </a>
                    </div>
                    <!-- Shunt Menu with submenu -->
                    <a href="#shunt_submenu" data-toggle="collapse" aria-expanded="false"
                       class="navbar-custom-light list-group-item list-group-item-action flex-column align-items-start">
                        <div class="d-flex w-100 justify-content-start align-items-center">
                            <img src="{% static 'Picto_Alstom_Mainline_RGB_Carbonblue.png' %}" height=24>
                            <span class="fa fa-dashboard fa-fw mr-3"></span>
                            <span class="menu-collapsed">Shunt</span>
                            <span class="submenu-icon ml-auto"></span>
                        </div>
                    </a>
                    <!-- Shunt Submenu content -->
                    <div id='shunt_submenu' class="collapse sidebar-submenu
                             {% block app_shunt_submenu_show %}

                             {% endblock %}">
                        <a href="{% url 'shunt:index' %}" class="list-group-item list-group-item-action
                                 navbar-custom-light
                                 {% block app_nav_item1 %}
                                 {% endblock %}">
                            <span class="menu-collapsed">Status</span>
                        </a>
                        <a href="{% url 'shunt:config' %}" class="list-group-item list-group-item-action
                                 navbar-custom-light
                                 {% block app_nav_item2 %}
                                 {% endblock %}">
                            <span class="menu-collapsed">Settings</span>
                        </a>
                        <a href="{% url 'csvbrowse:index' %}" class="list-group-item list-group-item-action
                                 navbar-custom-light
                                 {% block app_nav_item3 %}
                                 {% endblock %}">
                            <span class="menu-collapsed">App Files</span>
                        </a>
                    </div>
                    <!-- Shunt Submenu content -->
                    <!-- TCM Menu with submenu -->
                    <a href="#tcm_submenu" data-toggle="collapse" aria-expanded="false"
                       class="navbar-custom-light list-group-item list-group-item-action flex-column align-items-start">
                        <div class="d-flex w-100 justify-content-start align-items-center">
                            <img src="{% static 'Picto_Alstom_Infrastructure_RGB_Carbonblue.png' %}" height=24>
                            <span class="fa fa-dashboard fa-fw mr-3"></span>
                            <span class="menu-collapsed">TCM</span>
                            <span class="submenu-icon ml-auto"></span>
                        </div>
                    </a>
                    <!-- TCMA Submenu content -->
                    <div id='tcm_submenu' class="collapse sidebar-submenu
                             {% block app_tcm_submenu_show %}
                             {% endblock %}">
                        <a href="{% url 'tcm:index' %}" class="list-group-item list-group-item-action
                                 navbar-custom-light
                                 {% block tcm_nav_item1 %}
                                 {% endblock %}">
                            <span class="menu-collapsed">Status</span>
                        </a>
                        <a href="{% url 'tcm:config' %}" class="list-group-item list-group-item-action
                                 navbar-custom-light
                                 {% block tcm_nav_item2 %}
                                 {% endblock %}">
                            <span class="menu-collapsed">Settings</span>
                        </a>
                        <a href="{% url 'tcm:plot' %}" class="list-group-item list-group-item-action
                                 navbar-custom-light
                                 {% block tcm_nav_item3 %}
                                 {% endblock %}">
                            <span class="menu-collapsed">Plot</span>
                        </a>
                    </div>
                    <!-- TCMA Submenu content -->
                </ul><!-- List Group END-->
            </div><!-- sidebar-container END -->
            <!-- MAIN -->
            <div class="col p-4">
                {% block body %}
                {% endblock %}
            </div><!-- Main Col END -->
        </div><!-- body-row END -->
                    </div>
        {% block bodyscript %}
        {% endblock %}
    </body>
</html>