wsdmm_gui/apps/logcap/urls.py
###############################################################################
#  URL Dispatch for LogCap app
#
# Contact: andrew.vaselaar@alstomgroup.com
#
# COPYRIGHT
# | All rights reserved (c) 2020 ALSTOM, USA
# |
# | This computer program may not be used, copied, distributed,
# | corrected, modified, translated, transmitted or assigned
# | without ALSTOM's prior written authorization.
###############################################################################
from django.urls import path
from . import views

app_name = 'logcap'
urlpatterns = [
    path('', views.index, name='index'),
    path('config', views.config, name='config'),
    path('update', views.update, name='update'),
    path('logs/<int:timeframe>', views.logs, name='logs'),
    path('logs/', views.logs, name='logs'),
    path('config/startstop', views.startStop, name='startstop'),
    path('adddevice', views.addDevice, name='adddevice'),
    path('deldevice/<str:device_type>/<str:device_name>', views.delDevice, name='deldevice'),
    path('deviceconf/', views.showDeviceConf, name='deviceconf'),
    path('deviceconf/<str:device_type>/<str:device_name>', views.showDeviceConf, name='deviceconf'),
    path('adddeviceform/<str:device_type>', views.addDeviceForm, name='adddeviceform'),
    path('config/<str:device_type>/<str:device_name>', views.config, name='config'),
    path('rawlogs/', views.listRawLogs, name='rawlogs'),
    path('rawlogs/<str:device_type>/<str:device_name>', views.listRawLogs, name='rawlogs'),
    path('rawlogs/<str:device_type>/<str:device_name>/<str:filename>', views.listRawLogs, name='rawlogs'),
    path('rawlog/<str:device_type>/<str:device_name>/<str:filename>', views.rawLog, name='rawlog'),
    path('dlrawlog/<str:device_type>/<str:device_name>/<str:filename>', views.dlRawLog, name='dlrawlog'),
    path('dllatestraw/<str:device_type>/<str:device_name>', views.dlLatestRaw, name='dllatestraw'),
]

wsdmm_gui/wsdmm_gui/urls.py
##############################################################################
# Main WSDMM GUI URL Dispatch
#
# COPYRIGHT
# | All rights reserved (c) 2020, USA
# |
# | This computer program may not be used, copied, distributed,
# | corrected, modified, translated, transmitted or assigned
# | without ALSTOM's prior written authorization.
##############################################################################
"""wsdmm_gui URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('apps.main.urls')),
    path('admin/', admin.site.urls, name='admin'),
    path('shunt/', include('apps.shunt.urls')),
    path('shunt/csv/', include('apps.csvbrowse.urls')),
    path('logcap/', include('apps.logcap.urls')),
    path('tcm/', include('apps.tcm.urls')),
]

if bool(settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

wsdmm_gui/apps/logcap/models.py
###############################################################################
# The data model for the LogCap django app.
#
# The goal here is to provide just enough information for django to interact
# with the shunt NiFi app - nothing more.  All other data is stored in NiFi.
#
# COPYRIGHT
# | All rights reserved (c) 2020 ALSTOM, USA
# |
# | This computer program may not be used, copied, distributed,
# | corrected, modified, translated, transmitted or assigned
# | without ALSTOM's prior written authorization.
###############################################################################
from django.db import models


class LogCapServer(models.Model):
    # Hostname of the target LogCap instance
    hostname = models.CharField(max_length=256)
    # Port of the target LogCap instance
    hostport = models.IntegerField(default=8080)
    # Max Agg Log length (bytes)
    maxagglog = models.FloatField(default=10000000)

    def __str__(self):
        return self.hostname + ":" + str(self.hostport)

wsdmm_gui/apps/tcm/views.py
###############################################################################
# This is the django views modules for the TCM NiFi Django project.  It is
# intended to be used within a django app for managing a NiFi tcm install
# through its REST interface.
#
# Contact: andrew.vaselaar@alstomgroup.com
#
# COPYRIGHT
# | All rights reserved (c) 2020 ALSTOM, USA
# |
# | This computer program may not be used, copied, distributed,
# | corrected, modified, translated, transmitted or assigned
# | without ALSTOM's prior written authorization.
###############################################################################
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django import forms

from tempus_dominus.widgets import DateTimePicker

from common.wsdmmapi import wsdmmapi as wapi

from datetime import datetime, timedelta
import logging
import re
import json

api = wapi.wsdmmapi('tcm')
dbapi = wapi.wsdmmapi('influx')

logger = logging.getLogger(__name__)


@api.check
def index(request):
    r = api.get('status/service/tcm')
    if r.status_code == 200:
        data = r.json()
        status = {}
        for key in data['status']:
            status[key.replace('_', '')] = data['status'][key]
        context = {
            'hostname': data['hostname'],
            'port': data['hostport'],
            'service': data['service'],
            'status': status
        }
    else:
        context = {
            'hostname': 'none',
            'port': 'none',
            'service': 'none'
        }
    return render(request, 'tcm/index.html', context)


@api.check
def config(request, processor_name=''):
    track_ids = api.getTrackIDs('tcm')

    if processor_name == '':
        processor_name = track_ids[0]

    # Populate the processor List
    r = api.get('conf/tcm')
    data = r.json()
    nav = {}
    for item in data.items():
        nav[item[0]] = item[1]['name']

    # Populate the Form
    if len(processor_name) == 3 and re.match('[1-9]_[1-2]', processor_name):
        r = api.get('conf/tcm/track/' + processor_name)
    else:
        r = api.get('conf/tcm/mqtt/' + processor_name)
    data = r.json()
    context = {
        'status': 1,
        'track_ids': track_ids,
        'nav': nav,
        'pdispname': nav[processor_name],
        'fields': data,
        'processor': processor_name,
    }
    return render(request, 'tcm/config.html', context)


@api.check
def update(request):
    processor_name = request.POST['processor']
    url, name = api.pURLName(processor_name)
    r = api.get(url)
    fields = r.json()
    for key in fields:
        fields[key] = request.POST[key]
    r = api.postJSON(url, fields)
    return HttpResponseRedirect(reverse('tcm:config'))


@api.check
def startStop(request):
    if request.POST['control'] == "start":
        api.get('sched/tcm?desired_state=True')
    if request.POST['control'] == "stop":
        api.get('sched/tcm?desired_state=False')
    return HttpResponseRedirect(reverse('tcm:index'))


@api.check
@dbapi.check
def plot(request):
    # Empty dict for data
    data = {
        'meanCurrent': [],
        'operating_margin_max': [],
        'operating_margin_min': [],
        'blowby_threshold': [],
        'dropout_threshold': [],
        'reliability_margin': [],
        'safety_margin': [],
    }
    track_ids = api.getTrackIDs('tcm')

    # Start time/end time in datetime objects
    # IF this is in service in 2038, something has gone horribly wrong.
    time_format_string = "%Y-%m-%d %H:%M"
    timenow = datetime.today()
    if 'Begin' in request.GET:
        start_time = datetime.strptime(request.GET['Begin'], time_format_string)
    else:
        start_time = timenow - timedelta(seconds=24 * 60 * 60)  # default 1 day

    logger.debug(start_time)

    if 'End' in request.GET:
        end_time = datetime.strptime(request.GET['End'], time_format_string)
    else:
        end_time = timenow

    if 'track' in request.GET:
        track = request.GET['track']
    else:
        track = track_ids[0]

    # Which track do we want data for, and submit query
    if track in track_ids:
        r = api.get(str.format('data/tcm?startTime={}&endTime={}&track={}', int(start_time.timestamp()), int(end_time.timestamp()), track))
        if r.status_code == 200:
            plotdata = json.loads(r.json())
            for series in data:
                for x, value in plotdata.items():
                    data[series].append({'x': int(x) / 1000, 'y': value[series]})
        else:
            data = None

    form = dateForm()

    initial_date = {
        'start_time': start_time.strftime("%Y-%m-%d %H:%M"),
        'end_time': end_time.strftime("%Y-%m-%d %H:%M"),
    }

    context = {
        'track': track,
        'track_ids': track_ids,
        'initial_date': initial_date,
        'data': data,
        'form': form,
    }

    return render(request, 'tcm/plot.html', context)


class dateForm(forms.Form):
    Begin = forms.DateTimeField(
        widget=DateTimePicker(
            options={
                'format': "YYYY-MM-DD HH:mm",
                'collapse': False,
            },
            attrs={
                'append': 'fa fa-calendar',
                'icon_toggle': True,
            }
        ),
    )

    End = forms.DateTimeField(
        widget=DateTimePicker(
            options={
                'format': "YYYY-MM-DD HH:mm",
                'collapse': False,
            },
            attrs={
                'append': 'fa fa-calendar',
                'icon_toggle': True,
            }
        ),
    )

wsdmm_gui/apps/logcap/templates/logcap/adddeviceform.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>LogCap - Add New Device</title>
{% endblock %}

{% block nav-logcap %}
<li class="nav-item active p-2">
	<a class="nav-link" href="{% url 'logcap:index'%}">LogCap</a>
</li>
{% endblock %}

{% block app_nav_brand %}
<a class="navbar-brand" href="#"><h5>Logmon Monitoring</h5></a>
{% endblock %}

{% block app_logcap_submenu_show %}
show
{% endblock %}

{% block app_nav_item1 %}
{% endblock %}
{% block app_nav_item2 %}
active
{% endblock %}
{% block app_nav_item3 %}
{% endblock %}

{% block body %}
<div class="container-flex">
		<div class="col-sm-6">
			<h1>Add New {{device_type}}</h1>
			<hr class="mt-0 mb-4">
			<form action="{% url 'logcap:adddevice' %}" method="post">
				{% csrf_token %}
				<h3>{{ device_name }} Settings</h3>
				<div class="form-group">
					<table class="table">
						<tbody>
							<tr>
								<td><label for="device_name">Device Name</label></td>
								<td><input type="text" class="form-control form-control-sm" name="device_name" id="device_name" value=""></td>
							</tr>
							{% for key, value in form_elements.items %}
							{% if key in string_list %}
							<tr>
								<td><label for="{{ key }}">{{ key }}</label></td>
								<td style="min-width:400px"><input type="text" class="form-control form-control-sm" name="{{ key }}" id="{{ key }}" value="{{value}}"></td>
							</tr>
							{% elif key in num_list %}
							<tr>
								<td><label for="{{ key }}">{{ key }}</label></td>
								<td style="min-width:400px"><input type="text" class="form-control form-control-sm" name="{{ key }}" id="{{ key }}" value="{{value}}"></td>
							</tr>
							{% elif key in list_list %}
							<tr>
								<td><label for="{{ key }}">{{ key }}</label></td>
								<td style="min-width:400px"><input type="text" class="form-control form-control-sm" name="{{ key }}" id="{{ key }}" value="{% for item in value %}{{ item }},{% endfor %}"></td>
							</tr>
							{% endif %}
							{% endfor %}
						</tbody>
					</table>
					{% for key, value in form_elements.items %}
					{% if key in dict_list %}
					<div class="card">
						<div class="card-body">
							<h5 class="card-title">{{ key }}</h5>
							{% for inkey, invalue in value.items %}
							<label for="{{ inkey }}">{{ inkey }}</label>
							<input type="text" class="form-control form-control-sm" name="{{key}}.{{ inkey }}" id="{{key}}.{{ inkey }}" value="{{ invalue }}">
							{% endfor %}
						</div>
					</div>
					{% endif %}
					{% endfor %}

				</div>
				<input type="hidden" id="device_type" name="device_type" value="{{ device_type }}">
				<input type="submit" class="btn btn-primary" value="add">
			</form>
		</div>
	</div>
</div>
{% endblock %}

wsdmm_gui/apps/logcap/templates/logcap/config.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>LogCap Configuration</title>
{% endblock %}

{% block nav-logcap %}
<li class="nav-item active p-2">
	<a class="nav-link" href="{% url 'logcap:index'%}">LogCap</a>
</li>
{% endblock %}

{% block app_nav_brand %}
<a class="navbar-brand" href="#"><h5>Logmon Monitoring</h5></a>
{% endblock %}

{% block app_logcap_submenu_show %}
show
{% endblock %}

{% block logcap_nav_item1 %}
{% endblock %}
{% block logcap_nav_item2 %}
active
{% endblock %}
{% block logcap_nav_item3 %}
{% endblock %}
{% block logcap_nav_item4 %}
{% endblock %}

{% block body %}
<div class="container-flex">
	<div class="row justify-content-right">
		<div class="col-sm-3">
			<hr class="mt-0 mb-4">
			<h4>Devices</h4>
			<ul class="nav flex-column">
				{% for device_type, device_name in device_list %}
				<li class="nav-item">
					<a class="nav-link" href="{% url 'logcap:config' device_type device_name %}">{{ device_name }}</a>
				</li>
				{% endfor %}
			</ul>

			<div class="row justify-content-right">
				<div class="dropdown">
					<button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Add New Device
						<span class="caret"></span></button>
					<ul class="dropdown-menu">
						{% for device_type in supported_device_types %}
						<li><a href="{% url 'logcap:adddeviceform' device_type %}">{{ device_type }}</a></li>
						{% endfor %}
					</ul>
				</div>
				<div class="dropdown">
					<button class="btn btn-danger dropdown-toggle" type="button" data-toggle="dropdown">Delete Device
						<span class="caret"></span></button>

					<ul class="dropdown-menu">
						{% for device_type, device_name in device_list %}
						<li><a href="{% url 'logcap:deldevice' device_type device_name %}">{{device_type}} - {{ device_name }}</a></li>
						{% endfor %}
					</ul>
				</div>
			</div>
		</div>

		<div class="col-sm-6">
			<h1>Logmon Configuration</h1>
			<hr class="mt-0 mb-4">
			{% if status > 0 %}
			{% else %}
			<div class="alert alert-dark" role="alert">
				LogCap not available.
			</div>
			{% endif %}
			<form action="{% url 'logcap:update' %}" method="post">
				{% csrf_token %}
				<h3>{{ device_name }} Settings</h3>
				<div class="form-group">
					<table class="table">
						<tbody>
							{% for key, value in form_elements.items %}
							{% if key in string_list %}
							<tr>
								<td><label for="{{ key }}">{{ key }}</label></td>
								<td style="min-width:400px"><input type="text" class="form-control form-control-sm" name="{{ key }}" id="{{ key }}" value="{{value}}"></td>
							</tr>
							{% elif key in num_list %}
							<tr>
								<td><label for="{{ key }}">{{ key }}</label></td>
								<td style="min-width:400px"><input type="text" class="form-control form-control-sm" name="{{ key }}" id="{{ key }}" value="{{value}}"></td>
							</tr>
							{% elif key in list_list %}
							<tr>
								<td><label for="{{ key }}">{{ key }}</label></td>
								<td style="min-width:400px"><input type="text" class="form-control form-control-sm" name="{{ key }}" id="{{ key }}" value="{% for item in value %}{{ item }},{% endfor %}"></td>
							</tr>
							{% endif %}
							{% endfor %}
						</tbody>
					</table>
					{% for key, value in form_elements.items %}
					{% if key in dict_list %}
					<div class="card">
						<div class="card-body">
							<h5 class="card-title">{{ key }}</h5>
							{% for inkey, invalue in value.items %}
							<label for="{{ inkey }}">{{ inkey }}</label>
							<input type="text" class="form-control form-control-sm" name="{{key}}.{{ inkey }}" id="{{key}}.{{ inkey }}" value="{{ invalue }}">
							{% endfor %}
						</div>
					</div>
					{% endif %}
					{% endfor %}

				</div>
				<input type="hidden" id="device_name" name="device_name" value="{{ device_name }}">
				<input type="hidden" id="device_type" name="device_type" value="{{ device_type }}">
				<input type="submit" class="btn btn-primary" value="update">
			</form>
		</div>
	</div>
</div>
{% endblock %}

wsdmm_gui/apps/logcap/templates/logcap/logs.html
{% extends 'base.html' %}
{% load static %}


{% load crispy_forms_tags %}

{% block head %}
<title>LogCap</title>
{% endblock %}
{% block script %}
<script type="text/javascript" src="{% static "datatables/datatables.min.js" %}"></script>
<script type="text/javascript" src="{% static "datatables/DataTables-1.10.21/js/dataTables.jqueryui.min.js" %}"></script>
<script type="text/javascript" src="{% static "datatables/DataTables-1.10.21/js/dataTables.bootstrap4.min.js" %}"></script>
<script type="text/javascript" src="{% static "datatables/Buttons-1.6.2/js/dataTables.buttons.min.js" %}"></script>
<script type="text/javascript" src="{% static "datatables/Buttons-1.6.2/js/buttons.html5.min.js" %}"></script>
<script type="text/javascript" src="{% static "datatables/Buttons-1.6.2/js/buttons.bootstrap4.min.js" %}"></script>
<script type="text/javascript" src="{% static "gijgo/js/gijgo.min.js" %}"></script>
{{ form.media }}
<script type="text/javascript" class="init">
 var dataSet = {{ log_list|safe }};
 var log_tree = {{ log_tree|safe }};

 function post(path, method='post') {
     // copy data from the tree into hidden fields in the already existing
     // form, submit the form
     const form = document.getElementById('form_fields');
     form.method = method;
     form.action = path;

     var checkedIds = tree.getCheckedNodes();

     const hiddenField = document.createElement('input');
     hiddenField.type = 'hidden';
     hiddenField.name = 'logs';
     hiddenField.value = JSON.stringify(checkedIds);
     form.appendChild(hiddenField);
     form.submit()
 }


 function filterGlobal () {
     $('#example').DataTable().search(
         $('#global_filter').val(),
         $('#global_regex').prop('checked'),
         $('#global_smart').prop('checked')
     ).draw();
 }

 function filterColumn ( i ) {
     $('#example').DataTable().column( i ).search(
         $('#col'+i+'_filter').val(),
         $('#col'+i+'_regex').prop('checked'),
         $('#col'+i+'_smart').prop('checked')
     ).draw();
 }
 $(document).ready(function() {
     $('#example').DataTable( {
         data: dataSet,
         buttons: [
             'csv'
         ],
         select: true,
         "dom": 'tBilpr',
         columns: [
             { data: 'date', title:'Date' },
             { data: 'time', title:'Time' },
             { data: 'index', title:'Index', searchable: false },
             { data: 'deviceId', title:'Device ID' },
             { data: 'logSource', title:'Log Source' },
             { data: 'logEntry.data', title:'Log Data' },
         ]
     } );

     $('input.global_filter').on( 'keyup click', function () {
         filterGlobal();
     } );

     $('input.column_filter').on( 'keyup click', function () {
         filterColumn( $(this).parents('tr').attr('data-column') );
     } );

 } );


</script>
<style type="text/css">
</style>
{% endblock %}

{% block nav-logcap %}
<li class="nav-item active p-2">
    <a class="nav-link" href="{% url 'logcap:index'%}">LogCap</a>
</li>
{% endblock %}

{% block logcap_nav_brand %}
<a class="navbar-brand" href="#"><h5>LogCap Monitoring</h5></a>
{% endblock %}

{% block app_logcap_submenu_show %}
show
{% endblock %}

{% block logcap_nav_item1 %}
{% endblock %}
{% block logcap_nav_item2 %}
{% endblock %}
{% block logcap_nav_item3 %}
active
{% endblock %}
{% block logcap_nav_item4 %}
{% endblock %}

{% block body %}
<div class="container-flex">
    <form id="form_fields" autocomplete="off" action="{% url 'logcap:logs' %}" method='post'>
        {% csrf_token %}
        <div class="row justify-content-right">
            <div class="col-sm-3">
                <div class="mt-1">
                    <h3>Time Period</h3>
                    {{ form }}
                </div>
                <div class="mt-1">
                    <h3>Logs</h3>
                    <div id="tree"></div>
                </div>
                <div class="col-sm-2">
                </div>
                <div class="mt-1">
                    <button type="button" class="btn btn-primary" onclick="post('{% url 'logcap:logs' %}')">Get Logs</button>
                </div>
    </form>
            </div>
            <div class="col-sm-8 flex-sm-grow-1">
                <h3>Search and Filter</h3>
                <hr class="mt-0 mb-4">
                <table style="width: 100%; margin: 0 auto 0 auto;" cellspacing="0" cellpadding="2" border="0">
                    {% if status > 0 %}
                    <thead>
                        <tr>
                            <th>Target</th>
                            <th>Search text</th>
                            <th>Treat as regex</th>
                            <th>Use smart search</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr id="filter_global">
                            <td>Global search</td>
                            <td align="left"><input type="text" class="global_filter" id="global_filter" size=30></td>
                            <td align="center"><input type="checkbox" class="global_filter" id="global_regex"></td>
                            <td align="center"><input type="checkbox" class="global_filter" id="global_smart" checked="checked"></td>
                        </tr>
                        <tr id="filter_col1" data-column="0">
                            <td>Date</td>
                            <td align="left"><input type="text" class="column_filter" id="col0_filter" size=30></td>
                            <td align="center"><input type="checkbox" class="column_filter" id="col0_regex"></td>
                            <td align="center"><input type="checkbox" class="column_filter" id="col0_smart" checked="checked"></td>
                        </tr>
                        <tr id="filter_col2" data-column="1">
                            <td>Time</td>
                            <td align="left"><input type="text" class="column_filter" id="col1_filter" size=30></td>
                            <td align="center"><input type="checkbox" class="column_filter" id="col1_regex"></td>
                            <td align="center"><input type="checkbox" class="column_filter" id="col1_smart" checked="checked"></td>
                        </tr>
                        <tr id="filter_col3" data-column="3">
                            <td>Device ID</td>
                            <td align="left"><input type="text" class="column_filter" id="col3_filter" size=30></td>
                            <td align="center"><input type="checkbox" class="column_filter" id="col3_regex"></td>
                            <td align="center"><input type="checkbox" class="column_filter" id="col3_smart" checked="checked"></td>
                        </tr>
                        <tr id="filter_col4" data-column="4">
                            <td>Log Source</td>
                            <td align="left"><input type="text" class="column_filter" id="col4_filter" size=30></td>
                            <td align="center"><input type="checkbox" class="column_filter" id="col4_regex"></td>
                            <td align="center"><input type="checkbox" class="column_filter" id="col4_smart" checked="checked"></td>
                        </tr>
                        <tr id="filter_col5" data-column="5">
                            <td>Log Entry</td>
                            <td align="left"><input type="text" class="column_filter" id="col5_filter" size=30></td>
                            <td align="center"><input type="checkbox" class="column_filter" id="col5_regex"></td>
                            <td align="center"><input type="checkbox" class="column_filter" id="col5_smart" checked="checked"></td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="row justify-content-right">
                <div class="col-sm-2 flex-sm-grow-1">
                </div>
                <div class="col-sm-12 flex-sm-grow-1">
                    <div class="mt-4">
                        <table id="example" class="display" width="100%"></table>
                    </div>
                    {% elif status == -1 %}
                    <div class="mt-1">
                        Unknown device.
                    </div>
                    {% elif status == -2 %}
                    <div class="mt-1">
                        Too many logs, try a shorter period.
                    </div>
                    {% elif status == 0 %}
                    <div class="mt-1">
                        No Records Found
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
</div>
{% endblock %}
{% block bodyscript %}
<script>
 var tree = $('#tree').tree({
     dataSource: log_tree,
     checkboxes: true,
     cascadeCheck: true,
     hasChildrenField: 'haschildren',
     childrenField: 'logtypes',
     iconsLibrary: 'fontawesome',
     uiLibrary: 'bootstrap',
     border: false,
     primaryKey: 'id',
 });

 tree.collapseAll();

 {% if request_list %}
 var request_list = {{ request_list }};
 for(i = 0; i < request_list.length; i++){
     tree.check(tree.getNodeById(request_list[i]))
 }
 {% endif %}

 $('#id_Begin').datetimepicker('date', "{{ initial_date.start_time }}");
 $('#id_End').datetimepicker('date', "{{ initial_date.end_time }}");

</script>
{% endblock %}

wsdmm_gui/apps/logcap/templates/logcap/rawlog.html
<pre>{{ log }}</pre>

wsdmm_gui/apps/logcap/templates/logcap/rawlogs.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>Latest Raw Logs</title>
{% endblock %}

{% block script %}
{% endblock %}

{% block nav-logcap %}
<li class="nav-item active p-2">
<a class="nav-link" href="{% url 'logcap:index'%}">LogCap</a>
</li>
{% endblock %}

{% block app_nav_brand %}
<a class="navbar-brand" href="#"><h5>Logmon Monitoring</h5></a>
{% endblock %}

{% block app_logcap_submenu_show %}
show
{% endblock %}

{% block logcap_nav_item1 %}
{% endblock %}
{% block logcap_nav_item2 %}
{% endblock %}
{% block logcap_nav_item3 %}
{% endblock %}
{% block logcap_nav_item4 %}
{% endblock %}
{% block logcap_nav_item5 %}
active
{% endblock %}

{% block body %}
<div class="container-flex">
        <div class="row justify-content-right">
                <div class="col-sm-1 d-print-none flex-expand-1">
                        <h4>Devices</h4>
                        <hr class="mt-0 mb-4">
                        <nav class="navbar navbar-collapse">
                                <ul class="navbar-nav">
                                        {% for device_type, device_name in device_list %}
                                        <li class="nav-item"><a class="nav-link" href="{% url 'logcap:rawlogs' device_type device_name %}">{{ device_name }}</a></li>
                                        {% endfor %}
                                </ul>
                        </nav>
                </div>

                {% if device_name != '' %}
                <div class="col-sm-2 d-print-none flex-expand-1">
                        <h4>{{ device_name }} Latest Logs</h4>
                        <hr class="mt-0 mb-4">
                        <nav class="navbar navbar-collapse">
                                <div class="navbar-nav">
                                        <a class="nav-link" href="{% url 'logcap:dllatestraw' device_type device_name %}">Download All</a>
                                </div>
                        </nav>
                        <hr class="mt-0 mb-4">
                        <nav class="navbar navbar-collapse">
                                <div class="navbar-nav">
                                        {% for logtype, logname in log_menu.items|dictsort:0 %}
                                        <li class="nav-item"><a class="nav-link" href="{% url 'logcap:rawlogs' device_type device_name logname %}">{{ logtype }}</a></li>
                                        {% endfor %}
                                </div>
                        </nav>
                </div>
                {% endif %}
                {% if log %}
                <div class="col-sm-7 flex-sm-grow-1">
                        <div class="d-print-none">
                                <h4>{{ log_type }}</h4>
                                <hr class="mt-0 mb-4">
                                <nav class="navbar navbar-expand">
                                        <div class="navbar-nav">
                                                <a class="nav-item nav-link" href="{% url 'logcap:dlrawlog' device_type device_name filename %}">Download</a>
                                                <a class="nav-item nav-link" target="_blank" href="{% url 'logcap:rawlog' device_type device_name filename %}">View Raw</a>
                                        </div>
                                </nav>
                                <hr class="mt-0 mb-4">
                        </div>
                        <div class="d-print-none">
                                <pre>{{ log }}</pre>
                        </div>
                </div>
                {% endif %}
        </div>
</div>
<div class="d-none d-print-block">
        <pre>{{ log }}</pre>
</div>
{% endblock %}